package cn.probuing.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import java.util.List;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 */
@WebService(name = "ICustomerService", targetNamespace = "http://service.bos_crm.probuing.cn/")
@XmlSeeAlso({
//    ObjectFactory.class
})
public interface ICustomerService {


    /**
     * @return returns java.util.List<cn.probuing.bos.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findAll", targetNamespace = "http://service.bos_crm.probuing.cn/", className = "cn.probuing.bos.FindAll")
    @ResponseWrapper(localName = "findAllResponse", targetNamespace = "http://service.bos_crm.probuing.cn/", className = "cn.probuing.bos.FindAllResponse")
    public List<Customer> findAll();

    /**
     * @param arg0
     * @return returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findDecidedzoneIdByAddress", targetNamespace = "http://service.bos_crm.probuing.cn/", className = "cn.probuing.bos.FindDecidedzoneIdByAddress")
    @ResponseWrapper(localName = "findDecidedzoneIdByAddressResponse", targetNamespace = "http://service.bos_crm.probuing.cn/", className = "cn.probuing.bos.FindDecidedzoneIdByAddressResponse")
    public String findDecidedzoneIdByAddress(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * @param arg0
     * @return returns java.util.List<cn.probuing.bos.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findListHasAssociation", targetNamespace = "http://service.bos_crm.probuing.cn/", className = "cn.probuing.bos.FindListHasAssociation")
    @ResponseWrapper(localName = "findListHasAssociationResponse", targetNamespace = "http://service.bos_crm.probuing.cn/", className = "cn.probuing.bos.FindListHasAssociationResponse")
    public List<Customer> findListHasAssociation(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * @return returns java.util.List<cn.probuing.bos.Customer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findListNotAssociation", targetNamespace = "http://service.bos_crm.probuing.cn/", className = "cn.probuing.bos.FindListNotAssociation")
    @ResponseWrapper(localName = "findListNotAssociationResponse", targetNamespace = "http://service.bos_crm.probuing.cn/", className = "cn.probuing.bos.FindListNotAssociationResponse")
    public List<Customer> findListNotAssociation();

    /**
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "assigncustomerstodecidedzone", targetNamespace = "http://service.bos_crm.probuing.cn/", className = "cn.probuing.bos.Assigncustomerstodecidedzone")
    @ResponseWrapper(localName = "assigncustomerstodecidedzoneResponse", targetNamespace = "http://service.bos_crm.probuing.cn/", className = "cn.probuing.bos.AssigncustomerstodecidedzoneResponse")
    public void assigncustomerstodecidedzone(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    List<Integer> arg1);

    /**
     * @param arg0
     * @return returns cn.probuing.bos.Customer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCustomerByTelephone", targetNamespace = "http://service.bos_crm.probuing.cn/", className = "cn.probuing.bos.FindCustomerByTelephone")
    @ResponseWrapper(localName = "findCustomerByTelephoneResponse", targetNamespace = "http://service.bos_crm.probuing.cn/", className = "cn.probuing.bos.FindCustomerByTelephoneResponse")
    public Customer findCustomerByTelephone(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

}
